### ISSUE TITLE
EmuFog runtime exception - cannot resolve JCommander

### ISSUE THREAD

**Issue by renderfehler** [emufog/emufog#1]
`java -jar emufog-1.0.jar -s settings.json -t brite -f 5er.brite -o out.py`

Generates: 
```##############################################################
Welcome to EmuFog
##############################################################
Closing EmuFog
Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/JCommander
	at emufog.launcher.Emufog.main(Emufog.java:46)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.JCommander
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
`java -jar emufog-1.0-fat.jar -s settings.json -t brite -f 5er.brite -o out.py` is working fine. Why?

**Comment by MatiasNMont** [comment]
I have the same error, why is it?

**Comment by renderfehler** [comment]
Most likely you are missing the jcommander dependency in your classpath. 
The easiest solution is to compile the jar using the fatJar task in gradle.
